### ISSUE TITLE
Setting an icon theme doesn't work

### ISSUE THREAD

**Issue by PopeRigby** [oknozor/onagre#17]
`XDG_DATA_DIRS` is set to `/usr/local/share:/usr/share` and I have multiple icon themes in both of those directories, but setting `icons` to any of them in `~/.config/onagre/config.toml` doesn't work.

OS: Arch Linux
WM: Sway

**Comment by oknozor** [comment]
Can you provide a detailed setup so I can reproduce ? 

I would need the following : 
-  a copy of your icon themes (if they are home made, otherwise just the name of the theme so I can get it) 
- their detailed locations on your file system
- content of your `config.toml` file

**Comment by PopeRigby** [comment]
Yeah, sure.

Icon theme: [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)
Theme location: `/usr/share/icons/Papirus`
Contents of `config.toml`:
```
icons = "Papirus"
```

I also tried Adwaita and Breeze icons.

**Comment by oknozor** [comment]
@PopeRigby, I have tried to reproduce without success. 

I have updated the debug trace so we can see what is happening here. 
Can you update onagre, run in debug mode and send the debug trace here : 

```
cargo install --git https://github.com/oknozor/onagre
RUST_LOG=onagre=debug onagre &> trace
```

**Comment by PopeRigby** [comment]
Sure. Here you go: https://paste.ubuntu.com/p/QSrdfhWXp9/

**Comment by oknozor** [comment]
@PopeRigby seems your config is not loaded at all, the config load error should now print to stderr. You can update again 
and you should be able to troubleshot this without debug mode. Let me know how it goes.

**Comment by PopeRigby** [comment]
Ok, it gives me this error:
```
Unable to load config file : Config format error : missing field `modes`
```

**Comment by oknozor** [comment]
Fixed in 77f0663aeaa2b2ca7d1e78593402b976eef0d46c, you can update and icons will work :)

**Comment by PopeRigby** [comment]
Thanks!

**Comment by PopeRigby** [comment]
Weird, still doesn't work, but Onagre does seem to be finding the icon theme now:
```
[2020-11-27T22:39:34Z DEBUG onagre::freedesktop::icons] building icon finder for theme "Papirus"
[2020-11-27T22:39:34Z DEBUG onagre::freedesktop::icons] Initializing icon finder with icon theme path "/usr/share/icons/Papirus"
[2020-11-27T22:39:34Z DEBUG onagre::freedesktop::icons] Initializing icon finder with parent/fallback icon paths ["/usr/share/icons/breeze", "/usr/share/icons/hicolor"]
```

**Comment by oknozor** [comment]
What if you remove `$HOME/.cache/onagre-drun` and retry ?

**Comment by PopeRigby** [comment]
There we go, that fixes it. Thanks!
